predict/urls.py
from django.urls import path
from .views import *


app_name = "predict"

urlpatterns = [
    path('',home, name='home'),
    path('prediction_page/', predict, name='prediction_page'), #path url index
    path('predict/',predict_chances, name=''), #path url predict.html
    path("edit_predict/<int:id>",predict_edit, name="edit_predict"),
    path("update_predict/<int:id>",update_predict, name=""),
    path('results/', view_results, name='results'), # path url result.html
    path('login/', login_view, name='login-page'),
    path("criteria/",criteria, name='criteria'),
    path('logout/', logout_request,name='logout'),
    path('manage_water_basic/',manage_water_basic_view,name='manage_water'),
    path('add_water_basic/',add_water_basic,name='add_water_basic'),
    path('delete/<int:id>',water_delete,name='water_delete'),
    path('delete_predict/<int:id>',delete_predict,name='delete_predict'),
    path('edit_water_basic/<int:id>',edit_water_basic,name='edit_water_basic'),
    path('update_water_basic/<int:id>',update_water_basic,name=""),
    path('result',result,name='result'),
    path('get_predict/',show_predict_chances,name="submit_prediction"),
    path('test/',test,name="test")
    
  

    
]

water/urls.py
import imp
from django.contrib import admin
from django.urls import include, path

from django.contrib import admin  
from django.urls import path  
from django.urls.conf import include  
from django.conf import settings  
from django.conf.urls.static import static  


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict.urls')),
   
    
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

predict/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from matplotlib import image



class PredResults(models.Model):
    do = models.FloatField()
    bod = models.FloatField()
    tcb = models.FloatField()
    fcb = models.FloatField()
    nh3n = models.FloatField()
    classification = models.CharField(max_length=40)

    def __str__(self):
        return self.classification
    # แปลงภาษาต่างด้าวเป็นมนุษย์
    
class Water_Basic_Data(models.Model):
    water_source_name = models.TextField()
    province_name = models.TextField()
    area_size = models.TextField()
    water_source_characteristics = models.TextField()
    water_source_information = models.TextField()
    picture_water = models.ImageField(upload_to='images')
    
       
class Water_Image(models.Model):
    picture_id = models.IntegerField()
    picture_water = models.ImageField(upload_to='images')
    waterbasic_id = models.ForeignKey(to='Water_Basic_Data', on_delete=models.CASCADE)
  
class Admin(models.Model):
    User_id = models.TextField(max_length=10)
    FirstName = models.TextField(max_length=255,unique=True)
    LastName = models.TextField(max_length=100,unique=True)
    username = models.TextField(max_length=200,unique=True)
    Password = models.TextField(max_length=100,unique=True)
    

    
    

    


    

predict/forms.py
from django import forms

from .models import PredResults, Water_Basic_Data

class PickForm(forms.ModelForm):

    class Meta:
        model = PredResults
        fields = ('do', 'bod','tcb','fcb','nh3n')

# class UserImage(forms.ModelForm):  
#     class meta:  
#         # To specify the model to be used to create form  
#         models = Water_Basic_Data  
#         # It includes all the fields of model  
#         fields = '__all__'  
        
class Update_Water_Basic(forms.ModelForm):
    
    class Meta:
        model = Water_Basic_Data
        fields = ('water_source_name','province_name','area_size','water_source_characteristics','water_source_information')

predict/views.py
from asyncore import read
from csv import reader
from dataclasses import replace
from fileinput import filename
import json
from predict.knnModel import load_csv, predict_classification, str_column_to_float

from django.contrib.auth.forms import AuthenticationForm #add this

from django.shortcuts import render

import pandas as pd
from predict.forms import PickForm, Update_Water_Basic

from .models import PredResults, Water_Basic_Data
from django.contrib.auth import authenticate
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout #add this
from django.core.paginator import Paginator
from math import sqrt            
import numpy as np
import pandas as pd
from django.http import JsonResponse

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler




# method เพื่อให้ predict.html เป็นหน้าแรกของเว็บ
def predict(request):
    return render(request, 'predict.html')

def home(request):
    if 'q' in request.GET:
        q=request.GET['q']
        posts=Water_Basic_Data.objects.filter(water_source_name=q)
    else:
        posts=Water_Basic_Data.objects.all()
    # Pagintion
    paginator=Paginator(posts,5)
    page_number=request.GET.get('page')
    posts_obj=paginator.get_page(page_number)
    return render(request,'home.html',{'posts':posts_obj})


def delete_predict(request,id):
    delete = PredResults.objects.get(id=id)
    delete.delete()
    result = PredResults.objects.all()
    return render(request,'results.html',{"data":result})

        

def predict_user(request):
    return render(request, 'predict_user.html')


def update_predict(request,id):
    update = PredResults.objects.get(id=id)
    form= PickForm(request.POST,instance=update)
    if form.is_valid():
        form.save()
        messages.success(request,"Updated Successfully...!")
        return render(request,"edit_predict.html",{"edit_predicts":update}) 


def predict_edit(request,id):
    getstudentdeails=PredResults.objects.get(id=id)
    return render(request,'edit_predict.html',{"edit_predict":getstudentdeails})




#method predict_chances เป็น method ที่รับ จากฟอร์มใน result.html

def predict_chances(request):
    if request.method == "POST":
        if request.POST.get('do') and request.POST.get('bod') and request.POST.get('tcb') and request.POST.get('fcb') and request.POST.get('nh3n'):
            data = PredResults()
        
            data.do = request.POST.get('do')
            data.bod = request.POST.get('bod')
            data.tcb = request.POST.get('tcb')
            data.fcb = request.POST.get('fcb')
            data.nh3n = request.POST.get('nh3n')
            data.save()
   
    return render(request,'predict.html')


#method view_results method ที่ส่ง dataset แสดงผลการจำแนก render ไปยัง result.html
def view_results(request):
    # ส่งคำจำแนกและแสดงทั้งหมดไปยัง result.html ใน method view_result 
    contact_list = PredResults.objects.all()
    paginator = Paginator(contact_list, 20) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'results.html', {'page_obj': page_obj})
       

def surface(request):
    return render(request, 'surface.html')

  
def criteria(request):
    return render(request, 'criteria.html')


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return render(request,'home.html')
            else:
                messages.error(request,"ชื่อผู้ใช้หรือรหัสผ่านผิด")
        else:
             messages.error(request,"ชื่อผู้ใช้หรือรหัสผ่านผิด")
    form = AuthenticationForm()
    return render(request, 'login.html', context={"login_form":form})



def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.") 
    return redirect("predict:home")


def manage_water_basic_view(request):
    data = Water_Basic_Data.objects.all()
   
    return render(request,'water_basic_view.html', {"data":data})

def test(request):
    f = open('Accuracy.json')
    f1 = open('FoldAcc.json')
    data = json.load(f)
    data1 = json.load(f1)
    
    acc = str(round(data['Accuracy'],2))
    fold = list()
    for i in data1:
        for key,value in i.items():
            fold.append(str(round(value,2)))
    return render(request, 'test.html', { "data" : acc, "fold": fold })

def update_water_basic(request,id):
    update = Water_Basic_Data.objects.get(id=id)
    form = Update_Water_Basic(request.POST,instance=update)
    data = Water_Basic_Data()
    
   
    if form.is_valid():
        form.save()
        return render(request,'edit_water_basic.html',{'edit_water_basic':update})



def edit_water_basic(request,id):
    edit_water_basic = Water_Basic_Data.objects.get(id=id)
    return render(request,'edit_water_basic.html',{"edit_water_basic":edit_water_basic})

    
def add_water_basic(request):
    if request.method == "POST":
        if request.POST.get('water_source_name') and request.POST.get('province_name') and request.POST.get('area_size') and request.POST.get('water_source_characteristics') and request.POST.get('water_source_information'):
            data = Water_Basic_Data()

            
            if len(request.FILES) != 0:
                data.picture_water = request.FILES['image']
                data.save()
                  
            data.water_source_name = request.POST.get('water_source_name')
            data.province_name = request.POST.get('province_name')
            data.area_size = request.POST.get('area_size')
            data.water_source_characteristics = request.POST.get('water_source_characteristics')
            data.water_source_information = request.POST.get('water_source_information')
            data.save()
            return redirect("predict:add_water_basic")
    else:
        return render(request,'add_water_basic.html')
            

def water_delete(request,id):
    delete = Water_Basic_Data.objects.get(id=id)
    delete.delete()
    result = Water_Basic_Data.objects.all()
    
    return render(request,"water_basic_view.html",{"data":result})


        
        
#--------------------------------user---------------------------#
def result(request):
    return render(request, 'result.html')


datasets = pd.read_csv("water.csv")

features = datasets.drop(columns='class',axis = 1)
labels= datasets['class']


x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size=0.2) #,stratify=count_class,random_state=2)
# print(x_test)

scale =StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)
def most_common(lst):
    return max(set(lst), key=lst.count)

def euclidean(point, data):
    # Euclidean distance between points a & data
    return np.sqrt(np.sum((point - data)**2, axis=1))

class KNeighborsClassifier:
    def __init__(self, k=3, dist_metric=euclidean):
        self.k = k
        self.dist_metric = dist_metric
        
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
        print("ป้อนชุดข้อมูล New")
        
    def predict(self, X_test):
        neighbors = []
        for x in X_test:
            distances = self.dist_metric(x, self.X_train)
            y_sorted = [y for _, y in sorted(zip(distances, self.y_train))]
            neighbors.append(y_sorted[:self.k])
            print('class:' + repr(neighbors))
            # print(distances)
        return list(map(most_common, neighbors))
    
    
    # def classify(self,neighbors):
    #     neighbors = []
    #     for i in distances:
    #         neighbors.append(self.y_train[i[0]])
    #     print(neighbors[0]) #ตัด1[0]
        
        
#object of knn
knn =  KNeighborsClassifier(k=1) 
knn.fit(x_train,y_train)
# knn.predict(np.array([6.85,0.68,3400,1100]).reshape(1,4))
# print(x_train[0])

def predict_new(request):
    if request.method == "POST":
        if request.POST.get('do') and request.POST.get('bod') and request.POST.get('tcb') and request.POST.get('fcb') and request.POST.get('nh3n'):
            data = PredResults()
        
            data.do = request.POST.get('do')
            data.bod = request.POST.get('bod')
            data.tcb = request.POST.get('tcb')
            data.fcb = request.POST.get('fcb')
            data.nh3n = request.POST.get('nh3n')
   
        return render(request,'predict.html')
    
# x_new = scale.transform(x_new)
# result = knn.predict(x_new)
#     if result == 0:
#          print("")
#     else:
#         print("")
#     predict_new()

###################################################################



#------------------------------------------------------------------------------------------------------------

def show_predict_chances(request):
    filename = 'watersTest.csv'
    k = 3
    dataset = load_csv(filename)
    for i in range(len(dataset[0])-1):
        str_column_to_float(dataset, i)
        
    if request.POST.get('action') == 'post':
        test_data = list()
        # Receive data from client
        do = float(request.POST.get('do'))
        bod = float(request.POST.get('bod'))
        tcb = float(request.POST.get('tcb'))
        fcb = float(request.POST.get('fcb'))
        nh3n = float(request.POST.get('nh3n'))
        
        test_data = [do, bod, tcb, fcb, nh3n]
        
        prediction = predict_classification(dataset, test_data, k)
        # Unpickle model
        # model = pd.read_pickle(r"D:\โปรเจค Ai\วิจัย KNN\demo\prediction\KNNModel.pkl")

templates/add_water_basic.html
{% extends "base.html" %}


{% block main %}

<div class="container w-50 mt-5">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <div class="form-group">
            <label for="">ชื่อแหล่งน้ำ</label>
             <input type="text" name="water_source_name" class="form-control">
        </div>
        <div class="form-group">
            <label for="">ชื่อจัดหวัด</label>
             <input type="text" name="province_name" class="form-control">
        </div>
        <div class="form-group">
            <label for="">ขนาดพื้นที่</label>
             <input type="text" name="area_size" class="form-control">
        </div>
        <div class="form-group">
            <label for="">ลักษณะแหล่งน้ำ</label>
             <input type="text" name="water_source_characteristics" class="form-control">
        </div>
        <div class="form-group">
            <label for="">ข้อมูลแหล่งน้ำ</label>
            <textarea name="water_source_information" class="form-control" id="" cols="30" rows="10"></textarea>
        </div>
        <div class="form-group">
            <label for="">รูปภาพเกี่ยวกับน้ำ</label>
            <input type="file" class="form-control" name="image">
        </div> 
        <br>
        <input type="submit" value="เพิ่ม" class="btn btn-success">
    </form>
</div>


{% endblock %}

templates/edit_predict.html
{% extends "base.html" %}


{% block main %}

<!DOCTYPE html>
<head>
    <title>Edit & Update Page</title>
</head>
<body>
    <center>
        <br>
        <h1 style="color:#FFD700;">แก้ไขชุดข้อมูล</h1>
        <hr>
        <form method ="POST" action="/update_predict/{{edit_predict.id}}"> 
            {% csrf_token %}
        <table border="1">
            <tr>
                <td>ออกซิเจนละลาย(DO)</td>
                <td><input type= "text" class="form-controlo" name = "do" value="{{edit_predict.do}}"> </td>
            </tr>

            <tr>
                <td>ค่าความสกปรกในรูปสารอินทรีย์หรือบีโอดี (BOD)</td>
                <td><input type="text" class="form-controlo"  name = "bod" value="{{edit_predict.bod}}" ></td>
            </tr>

            <tr>
                <td>ปริมาณแบคทีเรียกลุ่มโคลิฟอร์มทั้งหมด (TCB)</td>
                <td><input type="text"  class="form-controlo" name = "tcb" value="{{edit_predict.tcb}}"></td>
            </tr> 

            <tr>
                <td>ปริมาณแบคทีเรียกลุ่มฟีคอลโคลิฟอร์ม (FCB)</td>
                <td><input type="text" class="form-controlo" name = "fcb" value="{{edit_predict.fcb}}"></td>
            </tr>

            <tr>
                <td>ปริมาณแอมโมเนีย ไนโตรเจน (NH3-N)</td>
                <td><input type="text" class="form-controlo"  name = "nh3n" value="{{edit_predict.nh3n}}"></td>

            </tr>

        </table>
        <input type="submit" value = "Update">
    </form>   
    </center>
</body>
</html>



{% endblock %}

templates/predict.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-info bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
        

              <li class="nav-item"> 
                <a class="nav-link text-white" href="/">หน้าแรก</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link text-white" href="/prediction_page">การวิเคราะห์คุณภาพน้ำ</a>
              </li>
              

          </ul>
   
        </div>

        <div>
          {% if user.is_authenticated %}
             {{user.username}}
              &nbsp;&nbsp;&nbsp;&nbsp;<a href="/logout" class="btn btn-danger" style="margin-right:60px;">ออกจากระบบ</a>
          {% else %}
                <a class="btn btn-success" href="/login" style="margin-right:60px;">เข้าสู่ระบบ</a>
          {% endif %}
        </div>
        
        <div class="row">
          <form>
            <div class="input-group">
                <input name="q" type="text" placeholder="ค้นหาชื่อแหล่งน้ำ" class="form-control" />
                <div style="margin-left:30px;">
                    <button class="btn btn-info">ค้นหา</button>
                </div>
            </div>
        </form>
        </div>
      </nav>
    

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">ผลการวิเคราะห์คุณภาพน้ำ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>ผลลัพธ์:</h5>
                <div>ออกซิเจนละลาย (DO): <span id="sl"></span></div>
                <div>ค่าความสกปรกในรูปสารอินทรีย์หรือบีโอดี (BOD): <span id="sw"></span></div>
                <div>ปริมาณแบคทีเรียกลุ่มโคลิฟอร์มทั้งหมด (TCB): <span id="pl"></span></div>
                <div>ปริมาณแบคทีเรียกลุ่มฟีคอลโคลิฟอร์ม (FCB): <span id="pw"></span></div>
                <div>ปริมาณแอมโมเนีย ไนโตรเจน (NH3-N): <span id="p"></span></div>

                <h5 class="pt-3">ผลการวิเคราะห์ระดับคุณภาพน้ำ:</h5>
                <div id="prediction"></div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <h1>วิเคราะห์คุณภาพน้ำ</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="do">ออกซิเจนละลาย (DO)</label>
                    <input type="text" step="0.1" class="form-control" id="do" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="bod">ค่าความสกปรกในรูปสารอินทรีย์หรือบีโอดี (BOD)</label>
                    <input type="text"step="0.1"  class="form-control" id="bod" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="tcb">ปริมาณแบคทีเรียกลุ่มโคลิฟอร์มทั้งหมด (TCB)</label>
                    <input type="text"step="0.1"  class="form-control" id="tcb" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="fcb">ปริมาณแบคทีเรียกลุ่มฟีคอลโคลิฟอร์ม (FCB)</label>
                    <input type="text" step="0.1" class="form-control" id="fcb" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="nh3">ปริมาณแอมโมเนีย ไนโตรเจน (NH3-N)</label>
                    <input type="text"step="0.1"  class="form-control" id="nh3n" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                do:$('#do').val(),
                bod:$('#bod').val(),
                tcb:$('#tcb').val(),
                fcb:$('#fcb').val(),
                nh3n:$('#nh3n').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['do']
                document.getElementById("sw").innerHTML = json['bod']
                document.getElementById("pl").innerHTML = json['fcb']
                document.getElementById("pw").innerHTML = json['tcb']
                document.getElementById("p").innerHTML = json['nh3n']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

templates/predict_user.html

{% block main %}
<!-- Modal -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
    

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>do: <span id="sl"></span></div>
                <div>bod: <span id="sw"></span></div>
                <div>tcb: <span id="pl"></span></div>
                <div>fcb: <span id="pw"></span></div>
                <div>nh3n: <span id="p"></span></div>

                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Water Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="do">DO</label>
                    <input type="number" class="form-control" id="do" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="bod">BOD</label>
                    <input type="number"  class="form-control" id="bod" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="tcb">TCB</label>
                    <input type="number"  class="form-control" id="tcb" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="fcb">FCB</label>
                    <input type="number"  class="form-control" id="fcb" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="nh3">NH3N</label>
                    <input type="number"  class="form-control" id="nh3n" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                do:$('#do').val(),
                bod:$('#bod').val(),
                tcb:$('#tcb').val(),
                fcb:$('#fcb').val(),
                nh3n:$('#nh3n').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("sl").innerHTML = json['do']
                document.getElementById("sw").innerHTML = json['bod']
                document.getElementById("pl").innerHTML = json['fcb']
                document.getElementById("pw").innerHTML = json['tcb']
                document.getElementById("p").innerHTML = json['nh3n']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

{% endblock %}


templates/result.html
{% extends'base.html' %}

{% block main %}
<br>
<div class"alert alert-success" role="alert">
    <h4 class = "alert-heading">ผลการจำแนก คือ {{result}}</h4>
    <p></p>
    <hr>
        <a href="/classify">
            <button type="button"class="btn-warnning" >ย้อนกลับ</button>

        </a>
    </div>

{% endblock %}

templates/ีuser.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-2">
        <form action="predict_page.html" method="POST" enctype="multipart/form-data">
        <form action="prediction_page.html" method="POST" enctype="multipart/form-data">
        <h4 class = "alert-heading">ผลการจำแนก คือ {{result}}</h4>
        <h4 class = "alert-heading">distance {{dis}} </h4>
    </div>
{% endblock %}